name: CI

on: [ push ]

jobs:
  upload:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [
          { "container": "rockylinux/rockylinux:8", "dnf_command": "dnf --assumeyes install make automake autoconf libtool mariadb-devel" },
          { "container": "rockylinux/rockylinux:9", "dnf_command": "dnf --assumeyes --enablerepo=devel install make automake autoconf libtool mariadb-devel" }
        ]

    container:
      image: ${{ matrix.versions.container }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: ${{ matrix.versions.dnf_command }}

      - name: Build the project
        run: |
          autoreconf -fvi;
          CFLAGS="-mavx2 -O3" bash configure;
          make;
          make install DESTDIR="$(pwd)/buildroot";
